#!/usr/bin/env python3
"""Validate efficient slide-level visual review evidence generated by Chromium."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import unicodedata
import zlib
from datetime import datetime
from html.parser import HTMLParser
from pathlib import Path

try:
    from PIL import Image
except ImportError:  # Keep a dependency-free PNG decoder for portable validation.
    Image = None


PROFILE_SPECS = {
    "normal": {"viewport": "1920x1080", "visual_viewport": "1920x1080", "screenshot": "1920x1080", "zoom": 1, "scale_mode": "none", "device_pixel_ratio": 1},
    "short": {"viewport": "1366x650", "visual_viewport": "1366x650", "screenshot": "1366x650", "zoom": 1, "scale_mode": "none", "device_pixel_ratio": 1},
    "zoom150": {"viewport": "1920x1080", "visual_viewport": "1280x720", "screenshot": "1920x1080", "zoom": 1.5, "scale_mode": "browser-page", "device_pixel_ratio": 1},
    "tablet": {"viewport": "1024x768", "visual_viewport": "1024x768", "screenshot": "1024x768", "zoom": 1, "scale_mode": "none", "device_pixel_ratio": 1},
    "mobile": {"viewport": "390x844", "visual_viewport": "390x844", "screenshot": "390x844", "zoom": 1, "scale_mode": "none", "device_pixel_ratio": 1},
}
BASE_PROFILES = ("normal", "short", "zoom150")
RESPONSIVE_PROFILES = BASE_PROFILES + ("tablet", "mobile")
CHECKS_BY_CHANGE = {
    "all": ("crop", "aspect_ratio", "resolution", "content_match", "completion", "overflow", "occlusion", "text", "text_bounds", "density", "controls"),
    "text": ("text", "text_bounds", "density"),
    "image": ("crop", "aspect_ratio", "resolution", "content_match", "completion"),
    "navigation": ("controls",),
}
AUTOMATION_CHECKS_BY_CHANGE = {
    "all": ("text_bounds", "container_density", "controls", "image_geometry"),
    "text": ("text_bounds", "container_density"),
    "image": ("image_geometry",),
    "navigation": ("controls",),
}
QUALITY_DIMENSIONS = (
    "story", "art_direction", "layout_rhythm", "typography",
    "imagery", "composition", "evidence", "presentation_utility",
)
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
VOID_TAGS = {
    "area", "base", "br", "col", "embed", "hr", "image", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}


class SlideParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.stack: list[str] = []
        self.slides: list[dict[str, object]] = []
        self.current: dict[str, object] | None = None
        self.slide_depth: int | None = None

    def handle_starttag(self, tag: str, attrs) -> None:
        values = dict(attrs)
        classes = set(values.get("class", "").split())
        if tag == "section" and "slide" in classes:
            identity_setting = (values.get("data-identity-review") or "").strip()
            self.current = {
                "title": (values.get("data-title") or "").strip(),
                "visual_critical": values.get("data-visual-critical") == "true",
                "identity_setting": identity_setting,
                "identity_metadata": False,
                "identity_semantic": False,
                "identity_required": identity_setting == "required",
                "identity_detection": "explicit" if identity_setting == "required" else "none",
            }
            self.slides.append(self.current)
            self.slide_depth = len(self.stack)
        if self.current is not None:
            metadata = any((values.get(name) or "").strip() for name in (
                "data-subject-id", "data-subject-name", "data-identity-reference", "data-identity-cues"
            ))
            declared_kind = (values.get("data-slide-kind") or values.get("data-content-kind") or "").strip().lower()
            semantic = declared_kind in {"character", "person", "cast", "member", "portrait", "named-subject"} or any(
                re.search(r"(?:^|-)(?:character|person|cast|member|portrait)(?:-|$)", token, re.I)
                or re.fullmatch(r"(?:profile-wrap|profile-gallery|profile-grid)", token, re.I)
                for token in classes
            )
            self.current["identity_metadata"] = bool(self.current["identity_metadata"] or metadata)
            self.current["identity_semantic"] = bool(self.current["identity_semantic"] or semantic)
            setting = str(self.current["identity_setting"])
            required = setting == "required" or bool(self.current["identity_metadata"]) or (
                setting != "not-applicable" and bool(self.current["identity_semantic"])
            )
            self.current["identity_required"] = required
            self.current["identity_detection"] = (
                "explicit" if setting == "required"
                else "subject-metadata" if self.current["identity_metadata"]
                else "semantic-markup" if self.current["identity_semantic"]
                else "none"
            )
        if tag not in VOID_TAGS:
            self.stack.append(tag)

    def handle_startendtag(self, tag: str, attrs) -> None:
        self.handle_starttag(tag, attrs)
        if tag not in VOID_TAGS:
            self.handle_endtag(tag)

    def handle_endtag(self, tag: str) -> None:
        for position in range(len(self.stack) - 1, -1, -1):
            if self.stack[position] == tag:
                del self.stack[position:]
                break
        if tag == "section" and self.current is not None and self.slide_depth == len(self.stack):
            self.current = None
            self.slide_depth = None


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def default_review_directory(deck: Path) -> Path:
    workspace_root = os.environ.get("BUILD_HTML_SLIDES_WORKSPACE_ROOT")
    if workspace_root:
        root = Path(workspace_root).expanduser().resolve()
    else:
        agent_home = os.environ.get("BUILD_HTML_SLIDES_AGENT_HOME")
        if not agent_home:
            agent_home = os.environ.get("CLAUDE_CONFIG_DIR") or os.environ.get("CLAUDE_HOME")
        if not agent_home:
            runs_from_claude = ".claude" in Path(__file__).resolve().parts
            agent_home = Path.home() / (".claude" if runs_from_claude else ".codex")
            if not runs_from_claude:
                agent_home = os.environ.get("CODEX_HOME", agent_home)
        root = Path(agent_home).expanduser().resolve() / "build-html-slides" / "workspaces"
    stem = unicodedata.normalize("NFKC", deck.stem)
    slug = re.sub(r"[^\w.-]+", "-", stem, flags=re.UNICODE).strip("-_.")[:48] or "deck"
    path_hash = hashlib.sha256(str(deck.resolve()).encode("utf-8")).hexdigest()[:10]
    return root / f"{slug}-{path_hash}" / "review"


def valid_hash(value: object) -> bool:
    return isinstance(value, str) and re.fullmatch(r"[0-9a-f]{64}", value) is not None


def valid_observation(value: object) -> bool:
    return isinstance(value, str) and len(value.strip()) >= 20 and len(set(value.strip().split())) >= 3


def required_checks(scope: str, identity_required: bool) -> tuple[str, ...]:
    checks = CHECKS_BY_CHANGE[scope]
    if identity_required and scope in {"all", "image"}:
        return checks + ("identity",)
    return checks


def validate_identity_targets(
    record: dict,
    deck_root: Path,
    number: int,
    identity_required: bool,
    errors: list[str],
) -> dict[str, dict]:
    targets = record.get("identity_targets")
    if not isinstance(targets, list):
        errors.append(f"slide {number} identity_targets must be an array")
        return {}
    if not identity_required:
        if targets or record.get("identity_review") not in ([], None):
            errors.append(f"slide {number} without identity review must not carry identity evidence")
        return {}
    if not targets:
        errors.append(f"slide {number} requires at least one identity target")
        return {}

    by_id: dict[str, dict] = {}
    for position, target in enumerate(targets, 1):
        if not isinstance(target, dict):
            errors.append(f"slide {number} identity target {position} must be an object")
            continue
        target_id = str(target.get("target_id", "")).strip()
        if not re.fullmatch(rf"slide-{number}-identity-[1-9]\d*", target_id) or target_id in by_id:
            errors.append(f"slide {number} identity target {position} has an invalid or duplicate target_id")
            continue
        by_id[target_id] = target
        if not str(target.get("subject_id", "")).strip() or not str(target.get("subject_name", "")).strip():
            errors.append(f"slide {number} identity target {target_id} needs subject_id and subject_name")
        if target.get("mode") not in {"primary", "contains"}:
            errors.append(f"slide {number} identity target {target_id} mode must be primary or contains")
        cues = target.get("cues")
        if not isinstance(cues, list) or len(cues) < 2 or any(not str(cue).strip() for cue in cues):
            errors.append(f"slide {number} identity target {target_id} needs at least two identity cues")

        resolved: dict[str, Path] = {}
        for kind in ("asset", "reference"):
            relative = target.get(f"{kind}_path")
            if not isinstance(relative, str) or not relative.strip():
                errors.append(f"slide {number} identity target {target_id} is missing {kind}_path")
                continue
            candidate = (deck_root / relative).resolve()
            if not candidate.is_relative_to(deck_root) or not candidate.is_file():
                errors.append(f"slide {number} identity target {target_id} {kind}_path is not a local bundle file")
                continue
            if kind == "reference" and candidate.suffix.lower() != ".webp":
                errors.append(f"slide {number} identity target {target_id} reference_path must be WebP")
            resolved[kind] = candidate
            supplied_hash = target.get(f"{kind}_sha256")
            if not valid_hash(supplied_hash) or supplied_hash != sha256(candidate):
                errors.append(f"slide {number} identity target {target_id} {kind}_sha256 mismatch")
        if resolved.get("asset") == resolved.get("reference") or (
            valid_hash(target.get("asset_sha256"))
            and target.get("asset_sha256") == target.get("reference_sha256")
        ):
            errors.append(f"slide {number} identity target {target_id} cannot use its candidate as the reference")
    return by_id


def validate_identity_review(
    entries: object,
    targets: dict[str, dict],
    number: int,
    label: str,
    errors: list[str],
) -> None:
    if not isinstance(entries, list):
        errors.append(f"{label} slide {number} identity_review must be an array")
        return
    by_id = {
        str(entry.get("target_id", "")): entry
        for entry in entries
        if isinstance(entry, dict)
    }
    if set(by_id) != set(targets) or len(entries) != len(targets):
        errors.append(f"{label} slide {number} identity_review must cover every identity target exactly once")
        return
    for target_id, target in targets.items():
        entry = by_id[target_id]
        if entry.get("subject_name") != target.get("subject_name"):
            errors.append(f"{label} slide {number} identity review {target_id} subject_name mismatch")
        if str(entry.get("verdict", "")).lower() != "pass":
            errors.append(f"{label} slide {number} identity review {target_id} did not pass")
        if not valid_observation(entry.get("observation")):
            errors.append(f"{label} slide {number} identity review {target_id} needs visible cue-based reasoning")


def paeth(left: int, up: int, upper_left: int) -> int:
    estimate = left + up - upper_left
    distances = (abs(estimate - left), abs(estimate - up), abs(estimate - upper_left))
    return (left, up, upper_left)[distances.index(min(distances))]


def png_info(path: Path) -> tuple[tuple[int, int], int, int]:
    data = path.read_bytes()
    if not data.startswith(PNG_SIGNATURE):
        raise ValueError("not a PNG image")
    if Image is not None:
        try:
            with Image.open(path) as image:
                if image.format != "PNG" or image.mode not in {"RGB", "RGBA"}:
                    raise ValueError("review capture must be an 8-bit RGB or RGBA PNG")
                dimensions = image.size
                image.verify()
            with Image.open(path) as image:
                rgb = image.convert("RGB")
                colors = rgb.getcolors(maxcolors=4)
                color_count = 5 if colors is None else len(colors)
                extrema = rgb.convert("L").getextrema()
            return dimensions, color_count, extrema[1] - extrema[0]
        except ValueError:
            raise
        except (OSError, SyntaxError) as exc:
            raise ValueError("corrupt PNG image data") from exc

    offset = len(PNG_SIGNATURE)
    dimensions: tuple[int, int] | None = None
    channels = 0
    image_data: list[bytes] = []
    saw_end = False
    while offset + 12 <= len(data):
        length = int.from_bytes(data[offset : offset + 4], "big")
        chunk_type = data[offset + 4 : offset + 8]
        payload_start = offset + 8
        payload_end = payload_start + length
        crc_end = payload_end + 4
        if crc_end > len(data):
            raise ValueError("truncated PNG chunk")
        payload = data[payload_start:payload_end]
        expected_crc = int.from_bytes(data[payload_end:crc_end], "big")
        if zlib.crc32(chunk_type + payload) & 0xFFFFFFFF != expected_crc:
            raise ValueError("invalid PNG checksum")
        if chunk_type == b"IHDR":
            if dimensions is not None or length != 13:
                raise ValueError("invalid PNG header")
            width = int.from_bytes(payload[0:4], "big")
            height = int.from_bytes(payload[4:8], "big")
            bit_depth, color_type, compression, filter_method, interlace = payload[8:13]
            if width < 1 or height < 1:
                raise ValueError("invalid PNG dimensions")
            if bit_depth != 8 or color_type not in {2, 6}:
                raise ValueError("review capture must be an 8-bit RGB or RGBA PNG")
            if compression != 0 or filter_method != 0 or interlace != 0:
                raise ValueError("unsupported PNG encoding")
            dimensions = (width, height)
            channels = 3 if color_type == 2 else 4
        elif chunk_type == b"IDAT":
            image_data.append(payload)
        elif chunk_type == b"IEND":
            saw_end = True
            break
        offset = crc_end
    if dimensions is None or not image_data or not saw_end:
        raise ValueError("incomplete PNG image")
    try:
        decoded = zlib.decompress(b"".join(image_data))
    except zlib.error as exc:
        raise ValueError("corrupt PNG image data") from exc
    width, height = dimensions
    row_bytes = width * channels
    if len(decoded) != (row_bytes + 1) * height:
        raise ValueError("invalid PNG scanline data")

    previous = bytearray(row_bytes)
    colors: set[tuple[int, int, int]] = set()
    minimum_luma = 255
    maximum_luma = 0
    cursor = 0
    sample_step = max(1, width * height // 4096)
    pixel_index = 0
    for _ in range(height):
        filter_type = decoded[cursor]
        cursor += 1
        raw = decoded[cursor : cursor + row_bytes]
        cursor += row_bytes
        if filter_type > 4:
            raise ValueError("invalid PNG row filter")
        current = bytearray(row_bytes)
        for index, value in enumerate(raw):
            left = current[index - channels] if index >= channels else 0
            up = previous[index]
            upper_left = previous[index - channels] if index >= channels else 0
            predictor = (0, left, up, (left + up) // 2, paeth(left, up, upper_left))[filter_type]
            current[index] = (value + predictor) & 0xFF
        for index in range(0, row_bytes, channels):
            if pixel_index % sample_step == 0:
                red, green, blue = current[index : index + 3]
                colors.add((red, green, blue))
                luma = (299 * red + 587 * green + 114 * blue) // 1000
                minimum_luma = min(minimum_luma, luma)
                maximum_luma = max(maximum_luma, luma)
            pixel_index += 1
        previous = current
    return dimensions, len(colors), maximum_luma - minimum_luma


def parse_size(value: object, field: str, errors: list[str]) -> tuple[int, int] | None:
    if not isinstance(value, str):
        errors.append(f"missing size description: {field}")
        return None
    match = re.fullmatch(r"\s*(\d+)x(\d+)\s*", value, re.I)
    if not match:
        errors.append(f"{field} must use WIDTHxHEIGHT: {value}")
        return None
    return tuple(map(int, match.groups()))


def validate_quality_score(
    manifest: dict,
    mode: str,
    slide_count: int,
    primary_reviewer_refs: set[str],
    errors: list[str],
) -> None:
    score = manifest.get("quality_score")
    if not isinstance(score, dict) or score.get("status") != "pass":
        errors.append("final phase requires a passing quality_score")
        return
    if not isinstance(score.get("reviewer"), str) or not score["reviewer"].strip():
        errors.append("quality_score needs a reviewer")
    reviewer_ref = score.get("reviewer_ref")
    if not isinstance(reviewer_ref, str) or len(reviewer_ref.strip()) < 8:
        errors.append("quality_score needs a stable reviewer_ref")
    elif mode == "full" and reviewer_ref.strip() in primary_reviewer_refs:
        errors.append("full quality_score reviewer_ref must differ from every primary visual reviewer_ref")
    dimensions = score.get("dimensions")
    if not isinstance(dimensions, dict):
        errors.append("quality_score dimensions must be an object")
        return
    values = []
    for dimension in QUALITY_DIMENSIONS:
        value = dimensions.get(dimension)
        if not isinstance(value, int) or isinstance(value, bool) or value < 0 or value > 3:
            errors.append(f"quality score {dimension} must be an integer from 0 to 3")
        else:
            values.append(value)
    if len(values) != len(QUALITY_DIMENSIONS):
        return
    total = sum(values)
    if score.get("total") != total:
        errors.append(f"quality_score total must equal dimension sum: {total}")
    if mode == "full" and (total < 20 or min(values) < 2):
        errors.append("full quality_score requires at least 20/24 with every dimension at least 2")
    weakest = score.get("weakest_slides")
    required_count = min(3, slide_count)
    if not isinstance(weakest, list) or len(set(weakest)) != required_count or any(
        not isinstance(number, int) or isinstance(number, bool) or number < 1 or number > slide_count for number in weakest
    ):
        errors.append(f"quality_score weakest_slides must contain {required_count} distinct valid slide numbers")
    if not valid_observation(score.get("notes")):
        errors.append("quality_score notes need a concrete review observation")


def validate_current_fingerprints(deck: Path, manifest: dict, errors: list[str]) -> None:
    renderer = Path(__file__).with_name("render_slides.js")
    try:
        result = subprocess.run(
            ["node", str(renderer), "--fingerprints", str(deck)],
            capture_output=True,
            text=True,
            check=False,
            timeout=120,
        )
    except FileNotFoundError:
        errors.append("source fingerprint verification failed because Node.js is unavailable")
        return
    except subprocess.TimeoutExpired:
        errors.append("source fingerprint verification exceeded 120 seconds")
        return
    if result.returncode:
        detail = (result.stderr or result.stdout).strip().splitlines()
        errors.append(f"source fingerprint verification failed: {detail[-1] if detail else 'unknown error'}")
        return
    try:
        actual = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        errors.append(f"source fingerprint output is invalid: {exc}")
        return
    expected = manifest.get("source_fingerprints", {})
    if actual.get("global_sha256") != expected.get("global_sha256"):
        errors.append("global source fingerprint does not match the current HTML")
    if actual.get("slides") != expected.get("slides"):
        errors.append("slide source fingerprints do not match the current HTML or local assets")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("deck", type=Path)
    parser.add_argument("manifest", type=Path, nargs="?")
    args = parser.parse_args()
    args.deck = args.deck.expanduser().resolve()
    args.manifest = (
        args.manifest.expanduser().resolve()
        if args.manifest is not None
        else default_review_directory(args.deck) / "review.json"
    )
    errors: list[str] = []
    if not args.deck.is_file():
        errors.append(f"deck not found: {args.deck}")
    if not args.manifest.is_file():
        errors.append(f"review manifest not found: {args.manifest}")
    if errors:
        return report(errors)

    deck_bytes = args.deck.read_bytes()
    try:
        deck_text = deck_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        return report([f"deck is not valid UTF-8: {exc}"])
    slide_parser = SlideParser()
    slide_parser.feed(deck_text)
    if not slide_parser.slides:
        return report(["deck has no slide sections"])
    titles = [str(slide["title"]) for slide in slide_parser.slides]
    if any(not title for title in titles):
        errors.append("every slide needs a non-empty data-title")

    try:
        manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        return report([f"invalid review manifest: {exc}"])
    if not isinstance(manifest, dict):
        return report(["review manifest root must be an object"])
    if manifest.get("schema_version") != 7:
        errors.append("schema_version must be 7; regenerate evidence with render_slides.js")
    mode = manifest.get("mode")
    if mode not in {"quick", "full"}:
        errors.append("mode must be 'quick' or 'full'")
        mode = "quick"
    review_risk = manifest.get("review_risk")
    if review_risk not in {"standard", "high"}:
        errors.append("review_risk must be 'standard' or 'high'")
        review_risk = "standard"
    phase = manifest.get("phase")
    if phase not in {"iteration", "final"}:
        errors.append("phase must be 'iteration' or 'final'")
        phase = "iteration"
    responsive = manifest.get("responsive")
    if not isinstance(responsive, bool):
        errors.append("responsive must be true or false")
        responsive = False
    profiles = RESPONSIVE_PROFILES if responsive else BASE_PROFILES
    change_type = manifest.get("change_type")
    if change_type not in CHECKS_BY_CHANGE:
        errors.append("change_type must be all, text, image, or navigation")
        change_type = "all"
    if manifest.get("deck_sha256") != hashlib.sha256(deck_bytes).hexdigest():
        errors.append("deck_sha256 does not match the reviewed HTML")

    render_run = manifest.get("render_run")
    generator_path = Path(__file__).with_name("render_slides.js")
    expected_generator_hash = sha256(generator_path) if generator_path.is_file() else ""
    if not isinstance(render_run, dict):
        errors.append("render_run must be an object generated by render_slides.js")
        render_run = {}
    if render_run.get("generator") != "render_slides.js":
        errors.append("render_run generator must be render_slides.js")
    if render_run.get("generator_sha256") != expected_generator_hash:
        errors.append("render_run generator_sha256 does not match the installed renderer")
    run_id = str(render_run.get("id", ""))
    if not re.fullmatch(r"[0-9a-fA-F-]{36}", run_id):
        errors.append("render_run id must be a UUID")
    if not str(render_run.get("browser", "")).lower().startswith("chromium "):
        errors.append("render_run browser must identify Chromium")
    try:
        datetime.fromisoformat(str(render_run.get("captured_at", "")).replace("Z", "+00:00"))
    except ValueError:
        errors.append("render_run captured_at must be an ISO timestamp")
    if render_run.get("strategy") not in {"full", "incremental"}:
        errors.append("render_run strategy must be full or incremental")
    if render_run.get("animations_disabled") is not True:
        errors.append("validation captures must disable motion in the browser-only render context")

    expected_slides = set(range(1, len(titles) + 1))
    rendered = render_run.get("rendered_slides")
    reused = render_run.get("reused_slides")
    requested = render_run.get("requested_slides")
    directly_changed = render_run.get("directly_changed_slides")
    for name, value in (("rendered_slides", rendered), ("reused_slides", reused), ("requested_slides", requested), ("directly_changed_slides", directly_changed)):
        if not isinstance(value, list) or any(not isinstance(number, int) or isinstance(number, bool) for number in value):
            errors.append(f"render_run {name} must be an integer array")
    rendered_set = set(rendered) if isinstance(rendered, list) else set()
    reused_set = set(reused) if isinstance(reused, list) else set()
    requested_set = set(requested) if isinstance(requested, list) else set()
    changed_set = set(directly_changed) if isinstance(directly_changed, list) else set()
    if rendered_set & reused_set or rendered_set | reused_set != expected_slides:
        errors.append("rendered_slides and reused_slides must partition the deck exactly")
    if render_run.get("strategy") == "full" and rendered_set != expected_slides:
        errors.append("full render strategy must render every slide")
    if render_run.get("strategy") == "incremental":
        expected_neighbors = {
            candidate
            for number in requested_set | changed_set
            for candidate in (number - 1, number, number + 1)
            if candidate in expected_slides
        }
        if not expected_neighbors <= rendered_set:
            errors.append("incremental render must include requested/changed slides and their immediate neighbors")

    source_fingerprints = manifest.get("source_fingerprints")
    if not isinstance(source_fingerprints, dict) or not valid_hash(source_fingerprints.get("global_sha256")):
        errors.append("source_fingerprints needs a valid global_sha256")
        source_fingerprints = {}
    slide_hashes = source_fingerprints.get("slides")
    expected_hash_keys = {str(number) for number in expected_slides}
    if not isinstance(slide_hashes, dict) or set(slide_hashes) != expected_hash_keys or any(
        not valid_hash(value) for value in slide_hashes.values()
    ):
        errors.append("source_fingerprints slides must contain one SHA-256 per slide")
        slide_hashes = {}
    if render_run.get("strategy") == "incremental" and source_fingerprints.get("previous_global_sha256") != source_fingerprints.get("global_sha256"):
        errors.append("incremental render cannot reuse slides after a global style/runtime change")

    viewport_specs = manifest.get("viewports")
    if not isinstance(viewport_specs, dict):
        errors.append("viewports must be an object")
        viewport_specs = {}
    if tuple(viewport_specs) != profiles:
        errors.append(f"validation requires exactly these ordered profiles: {', '.join(profiles)}")
    screenshot_sizes: dict[str, tuple[int, int]] = {}
    for profile in profiles:
        supplied = viewport_specs.get(profile)
        expected = PROFILE_SPECS[profile]
        if not isinstance(supplied, dict):
            errors.append(f"missing viewport profile: {profile}")
            continue
        for field in ("viewport", "visual_viewport", "screenshot"):
            size = parse_size(supplied.get(field), f"{profile}.{field}", errors)
            if supplied.get(field) != expected[field]:
                errors.append(f"{profile}.{field} must be {expected[field]}")
            if field == "screenshot" and size is not None:
                screenshot_sizes[profile] = size
        if supplied.get("zoom") != expected["zoom"]:
            errors.append(f"{profile}.zoom must be {expected['zoom']}")
        for field in ("scale_mode", "device_pixel_ratio"):
            if supplied.get(field) != expected[field]:
                errors.append(f"{profile}.{field} must be {expected[field]}")

    automation_gate = manifest.get("automation_gate")
    if not isinstance(automation_gate, dict):
        errors.append("automation_gate must be an object")
        automation_gate = {}
    if automation_gate.get("checks") != list(AUTOMATION_CHECKS_BY_CHANGE[change_type]):
        errors.append("automation_gate checks do not match the current change type")
    automation_failures = automation_gate.get("failures")
    automation_warnings = automation_gate.get("warnings")
    if automation_gate.get("status") != "pass" or automation_failures != []:
        errors.append("automation_gate must pass before AI visual review")
    if not isinstance(automation_warnings, list):
        errors.append("automation_gate warnings must be an array")
        automation_warnings = []

    expected_ai_profiles: dict[int, list[str]] = {}
    for number in sorted(rendered_set):
        expected_critical = number in {1, len(titles)} or bool(
            slide_parser.slides[number - 1]["visual_critical"]
        )
        required_profiles: set[str] = set()
        if mode == "full":
            required_profiles.add("normal")
            if responsive:
                required_profiles.update(("tablet", "mobile"))
        if expected_critical:
            required_profiles.update(profiles)
        if bool(slide_parser.slides[number - 1]["identity_required"]) and change_type in {"all", "image"}:
            required_profiles.add("normal")
        slide_warning_profiles = {
            warning.get("profile")
            for warning in automation_warnings
            if isinstance(warning, dict)
            and warning.get("slide") == number
            and warning.get("profile") in profiles
        }
        if slide_warning_profiles:
            required_profiles.add("normal")
            required_profiles.update(slide_warning_profiles)
        expected_ai_profiles[number] = [profile for profile in profiles if profile in required_profiles]
    expected_ai_slides = {number for number, required in expected_ai_profiles.items() if required}

    review_batches = manifest.get("review_batches")
    if not isinstance(review_batches, list):
        errors.append("review_batches must be an array")
        review_batches = []
    batch_by_slide: dict[int, tuple[str, object]] = {}
    batch_ids: set[str] = set()
    for position, batch in enumerate(review_batches, 1):
        if not isinstance(batch, dict):
            errors.append(f"review batch {position} must be an object")
            continue
        batch_id = str(batch.get("id", ""))
        slides = batch.get("slides")
        capture_profiles = batch.get("capture_profiles")
        if not batch_id or batch_id in batch_ids:
            errors.append(f"review batch {position} needs a unique id")
        batch_ids.add(batch_id)
        if not isinstance(slides, list) or not 1 <= len(slides) <= 4 or any(
            not isinstance(number, int) or isinstance(number, bool) for number in slides
        ):
            errors.append(f"review batch {batch_id or position} must contain one to four slide numbers")
            continue
        if not isinstance(capture_profiles, dict) or set(capture_profiles) != {str(number) for number in slides}:
            errors.append(f"review batch {batch_id} capture_profiles must match its slides")
            capture_profiles = {}
        for number in slides:
            if number in batch_by_slide:
                errors.append(f"slide {number} appears in more than one review batch")
            batch_by_slide[number] = (batch_id, capture_profiles.get(str(number)))
    if set(batch_by_slide) != expected_ai_slides:
        errors.append("review_batches must partition exactly the refreshed slides routed to AI review")

    records = manifest.get("slides")
    if not isinstance(records, list):
        return report(errors + ["slides must be an array"])
    by_number: dict[int, dict] = {}
    for position, record in enumerate(records, 1):
        if not isinstance(record, dict):
            errors.append(f"review record {position} must be an object")
            continue
        number = record.get("slide")
        if not isinstance(number, int) or isinstance(number, bool):
            errors.append(f"review record {position} needs an integer slide number")
        elif number in by_number:
            errors.append(f"duplicate review record for slide {number}")
        else:
            by_number[number] = record
    for number in sorted(expected_slides - set(by_number)):
        errors.append(f"slide {number} has no visual review record")
    for number in sorted(set(by_number) - expected_slides):
        errors.append(f"review record references nonexistent slide {number}")

    evidence_root = args.manifest.parent.resolve()
    deck_mtime = args.deck.stat().st_mtime_ns
    capture_paths: set[Path] = set()
    capture_hashes: dict[int, dict[str, str]] = {}
    primary_refs: dict[int, str] = {}
    observations: list[str] = []
    for number in sorted(expected_slides & set(by_number)):
        record = by_number[number]
        if str(record.get("title", "")).strip() != titles[number - 1]:
            errors.append(f"slide {number} title mismatch: expected '{titles[number - 1]}'")
        source_hash = record.get("source_sha256")
        if source_hash != slide_hashes.get(str(number)):
            errors.append(f"slide {number} source_sha256 does not match its current source fingerprint")
        scope = record.get("review_scope")
        if scope not in CHECKS_BY_CHANGE:
            errors.append(f"slide {number} review_scope must be all, text, image, or navigation")
            scope = "all"
        expected_identity_required = bool(slide_parser.slides[number - 1]["identity_required"])
        if record.get("identity_required") is not expected_identity_required:
            errors.append(f"slide {number} identity_required does not match the HTML contract")
        expected_identity_detection = str(slide_parser.slides[number - 1]["identity_detection"])
        if record.get("identity_detection") != expected_identity_detection:
            errors.append(f"slide {number} identity_detection does not match automatic HTML classification")
        identity_targets = validate_identity_targets(
            record, args.deck.parent.resolve(), number, expected_identity_required, errors
        )

        reviewer = str(record.get("reviewer", "")).strip()
        reviewer_ref = str(record.get("reviewer_ref", "")).strip()
        current_ai_review = number in expected_ai_slides
        current_automation_only = number in rendered_set and not current_ai_review and mode == "quick"
        automation_only = current_automation_only or (
            number not in rendered_set and record.get("review_method") == "automated-geometry-only"
        )
        if automation_only:
            if reviewer or reviewer_ref:
                errors.append(f"quick slide {number} routed to automation only must not claim an AI reviewer")
            if record.get("review_method") != "automated-geometry-only":
                errors.append(f"quick slide {number} must use automated-geometry-only review")
        else:
            primary_refs[number] = reviewer_ref
            if not reviewer or len(reviewer_ref) < 8 or reviewer_ref == reviewer:
                errors.append(f"slide {number} needs reviewer and stable reviewer_ref")
            if record.get("review_method") != "vision-batched-full-size":
                errors.append(f"slide {number} review_method must be 'vision-batched-full-size'")

        captures = record.get("captures")
        if not isinstance(captures, dict) or tuple(captures) != profiles:
            errors.append(f"slide {number} must retain exactly these capture profiles: {', '.join(profiles)}")
            captures = captures if isinstance(captures, dict) else {}
        capture_hashes[number] = {}
        for profile in profiles:
            capture = captures.get(profile)
            if not isinstance(capture, dict):
                errors.append(f"slide {number} {profile} capture must be an object")
                continue
            relative = capture.get("path")
            if not isinstance(relative, str) or not relative.strip():
                errors.append(f"slide {number} is missing {profile} capture path")
                continue
            capture_path = (evidence_root / relative).resolve()
            if not capture_path.is_relative_to(evidence_root):
                errors.append(f"slide {number} {profile} capture escapes review directory")
                continue
            if capture_path in capture_paths:
                errors.append(f"slide {number} reuses capture evidence: {relative}")
                continue
            capture_paths.add(capture_path)
            if not capture_path.is_file():
                errors.append(f"slide {number} {profile} capture not found: {relative}")
                continue
            try:
                dimensions, color_count, luma_range = png_info(capture_path)
            except (OSError, ValueError) as exc:
                errors.append(f"slide {number} {profile} capture is invalid: {exc}")
                continue
            expected_dimensions = screenshot_sizes.get(profile)
            if expected_dimensions is not None and dimensions != expected_dimensions:
                errors.append(
                    f"slide {number} {profile} capture dimensions {dimensions[0]}x{dimensions[1]} "
                    f"do not match {expected_dimensions[0]}x{expected_dimensions[1]}"
                )
            if color_count < 4 or luma_range < 8:
                errors.append(f"slide {number} {profile} capture appears blank or near-solid")
            actual_hash = sha256(capture_path)
            if capture.get("sha256") != actual_hash:
                errors.append(f"slide {number} {profile} capture sha256 mismatch")
            capture_hashes[number][profile] = actual_hash
            if capture.get("active_slide") != number or capture.get("active_title") != titles[number - 1]:
                errors.append(f"slide {number} {profile} active slide evidence does not match the HTML")
            for field in (
                "viewport", "visual_viewport", "screenshot", "zoom", "scale_mode", "device_pixel_ratio"
            ):
                if capture.get(field) != PROFILE_SPECS[profile][field]:
                    errors.append(f"slide {number} {profile} capture {field} does not match the canonical profile")
            if capture.get("source_sha256") != source_hash:
                errors.append(f"slide {number} {profile} capture source fingerprint mismatch")
            if capture.get("motion_disabled") is not True:
                errors.append(f"slide {number} {profile} capture did not disable validation-only motion")
            if number in rendered_set:
                if capture.get("render_run_id") != run_id:
                    errors.append(f"slide {number} {profile} was not refreshed in the current render run")
                if capture_path.stat().st_mtime_ns < deck_mtime:
                    errors.append(f"slide {number} {profile} refreshed capture is older than the reviewed HTML")
                if scope in {"all", "text"}:
                    geometry = capture.get("text_geometry")
                    if not isinstance(geometry, dict) or geometry.get("ok") is not True or geometry.get("issues"):
                        errors.append(f"slide {number} {profile} deterministic text-bound geometry did not pass")
                    density = capture.get("container_density")
                    if not isinstance(density, dict) or density.get("ok") is not True or density.get("issues"):
                        errors.append(f"slide {number} {profile} container-density measurement did not pass")
                if scope in {"all", "navigation"}:
                    geometry = capture.get("control_geometry")
                    if not isinstance(geometry, dict) or geometry.get("ok") is not True or geometry.get("issues"):
                        errors.append(f"slide {number} {profile} rendered control geometry did not pass")
                if scope in {"all", "image"}:
                    geometry = capture.get("image_geometry")
                    if not isinstance(geometry, dict) or geometry.get("ok") is not True or geometry.get("issues"):
                        errors.append(f"slide {number} {profile} rendered image geometry did not pass")

        inspected_profiles = record.get("inspected_profiles")
        if number in rendered_set:
            expected_critical = number in {1, len(titles)} or bool(slide_parser.slides[number - 1]["visual_critical"])
            if record.get("visual_critical") is not expected_critical:
                errors.append(f"slide {number} visual_critical does not match the HTML/cover/closing contract")
            ordered_required = expected_ai_profiles[number]
            if record.get("required_ai_profiles") != ordered_required:
                errors.append(f"slide {number} required_ai_profiles do not match adaptive review routing")
            if current_automation_only:
                if inspected_profiles != [] or record.get("review_batch_id") or record.get("observation"):
                    errors.append(f"quick slide {number} automation-only record must not claim vision inspection")
                if record.get("checks") != {} or record.get("status") != "automation-pass":
                    errors.append(f"quick slide {number} automation-only record must carry automation-pass status")
            else:
                if inspected_profiles != ordered_required:
                    errors.append(f"slide {number} AI review must inspect its adaptive profile set once")
                batch_id, batch_profiles = batch_by_slide.get(number, ("", None))
                if record.get("review_batch_id") != batch_id or batch_profiles != ordered_required:
                    errors.append(f"slide {number} review batch does not bind its adaptive capture set")
                observation = record.get("observation")
                if not valid_observation(observation):
                    errors.append(f"slide {number} needs one concrete slide-level vision observation")
                else:
                    observations.append(observation.strip())
                checks = record.get("checks")
                expected_checks = required_checks(scope, expected_identity_required)
                if not isinstance(checks, dict) or tuple(checks) != expected_checks:
                    errors.append(f"slide {number} checks must match its {scope} review scope exactly")
                else:
                    for check in expected_checks:
                        if str(checks.get(check, "")).lower() != "pass":
                            errors.append(f"slide {number} check did not pass: {check}")
                if expected_identity_required and scope in {"all", "image"}:
                    validate_identity_review(
                        record.get("identity_review"), identity_targets, number, "primary review", errors
                    )
                elif record.get("identity_review") not in ([], None):
                    errors.append(f"slide {number} identity_review is out of scope for a {scope} change")
        expected_status = "automation-pass" if automation_only else "pass"
        if str(record.get("status", "")).lower() != expected_status:
            errors.append(f"slide {number} overall status must be {expected_status}")
    if len(observations) != len(set(observations)):
        errors.append("rendered slides must not reuse the same AI observation")

    distinct_primary_refs = {reference for reference in primary_refs.values() if reference}
    minimum_reviewers = 1 if mode == "quick" else (3 if review_risk == "high" else 2)
    if len(distinct_primary_refs) < minimum_reviewers:
        errors.append(f"{mode} validation requires at least {minimum_reviewers} distinct primary reviewer_ref values")
    if mode == "full" or len(distinct_primary_refs) > 1:
        for reference in distinct_primary_refs:
            assigned = sorted(number for number, value in primary_refs.items() if value == reference)
            if assigned and assigned != list(range(assigned[0], assigned[-1] + 1)):
                errors.append(f"reviewer_ref {reference!r} slide assignment is not contiguous")

    if phase == "final" and mode == "full":
        validate_quality_score(manifest, mode, len(titles), distinct_primary_refs, errors)

    cross_reviews = manifest.get("cross_reviews")
    if not isinstance(cross_reviews, list):
        errors.append("cross_reviews must be an array")
        cross_reviews = []
    cross_by_slide: dict[int, dict] = {}
    for position, review in enumerate(cross_reviews, 1):
        if not isinstance(review, dict):
            errors.append(f"cross review {position} must be an object")
            continue
        number = review.get("slide")
        if not isinstance(number, int) or isinstance(number, bool) or number not in expected_slides:
            errors.append(f"cross review {position} references an invalid slide")
            continue
        if number in cross_by_slide:
            errors.append(f"duplicate cross review for slide {number}")
            continue
        cross_by_slide[number] = review
    required_cross = set(expected_slides) if phase == "final" and mode == "full" else set()
    if phase == "final" and mode == "full":
        for number in sorted(required_cross - set(cross_by_slide)):
            errors.append(f"slide {number} requires an independent final cross review")
    for number, review in cross_by_slide.items():
        reviewer = str(review.get("reviewer", "")).strip()
        reviewer_ref = str(review.get("reviewer_ref", "")).strip()
        if not reviewer or len(reviewer_ref) < 8 or reviewer_ref == reviewer:
            errors.append(f"cross review slide {number} needs reviewer and stable reviewer_ref")
        if reviewer_ref in distinct_primary_refs:
            errors.append(f"cross review slide {number} reviewer_ref must be outside the primary reviewer set")
        required_profiles = by_number.get(number, {}).get("required_ai_profiles", [])
        if review.get("review_method") != "vision-batched-full-size":
            errors.append(f"cross review slide {number} review_method must be 'vision-batched-full-size'")
        if review.get("inspected_profiles") != required_profiles:
            errors.append(f"cross review slide {number} must inspect its adaptive profiles once")
        if not valid_observation(review.get("observation")):
            errors.append(f"cross review slide {number} needs one concrete observation")
        supplied_hashes = review.get("capture_sha256")
        if not isinstance(supplied_hashes, dict) or (
            set(supplied_hashes) != set(required_profiles) or any(
                supplied_hashes.get(profile) != capture_hashes.get(number, {}).get(profile)
                for profile in required_profiles
            )
        ):
            errors.append(f"cross review slide {number} capture hashes do not match current evidence")
        scope = by_number.get(number, {}).get("review_scope", "all")
        checks = review.get("checks")
        identity_required = bool(by_number.get(number, {}).get("identity_required"))
        expected_checks = required_checks(scope, identity_required)
        if not isinstance(checks, dict) or tuple(checks) != expected_checks or any(
            str(checks.get(check, "")).lower() != "pass" for check in expected_checks
        ):
            errors.append(f"cross review slide {number} checks did not pass its review scope")
        if identity_required and scope in {"all", "image"}:
            targets = {
                str(target.get("target_id")): target
                for target in by_number.get(number, {}).get("identity_targets", [])
                if isinstance(target, dict)
            }
            validate_identity_review(
                review.get("identity_review"), targets, number, "cross review", errors
            )
        if str(review.get("status", "")).lower() != "pass":
            errors.append(f"cross review slide {number} overall status did not pass")

    cross_observations = [
        str(review.get("observation", "")).strip()
        for review in cross_by_slide.values()
        if valid_observation(review.get("observation"))
    ]
    if len(cross_observations) != len(set(cross_observations)):
        errors.append("cross-reviewed slides must not reuse the same observation")

    if not errors and os.environ.get("BUILD_HTML_SLIDES_UNIT_TEST") != "1":
        validate_current_fingerprints(args.deck.resolve(), manifest, errors)
    if errors:
        return report(errors)
    score_message = " with final quality score" if phase == "final" and mode == "full" else " without quality scoring"
    print(
        f"OK: {args.manifest} - {len(rendered_set)} refreshed slides use adaptive AI review in "
        f"{len(review_batches)} batch(es) with {len(profiles)} retained profiles{score_message}"
    )
    return 0


def report(errors: list[str]) -> int:
    for error in errors:
        print(f"ERROR: {error}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
