#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="$ROOT/codex/skills/build-html-slides/"
ARCHIFY_SOURCE="$ROOT/codex/skills/archify/"
PLUGIN="$ROOT/plugins/build-html-slides/skills/build-html-slides/"
PLUGIN_ARCHIFY="$ROOT/plugins/build-html-slides/skills/archify/"
CLAUDE="$ROOT/.claude/skills/build-html-slides/"
CLAUDE_ARCHIFY="$ROOT/.claude/skills/archify/"
GEMINI="$ROOT/.gemini/skills/build-html-slides/"
GEMINI_ARCHIFY="$ROOT/.gemini/skills/archify/"

rsync -a --delete "$SOURCE" "$PLUGIN"
mkdir -p "$PLUGIN_ARCHIFY"
rsync -a --delete "$ARCHIFY_SOURCE" "$PLUGIN_ARCHIFY"
cp "$ROOT/LICENSE" "$ROOT/THIRD_PARTY_NOTICES.md" "$ROOT/plugins/build-html-slides/"
mkdir -p "$CLAUDE"
rsync -a --delete "$SOURCE" "$CLAUDE"
mkdir -p "$CLAUDE_ARCHIFY"
rsync -a --delete "$ARCHIFY_SOURCE" "$CLAUDE_ARCHIFY"
mkdir -p "$GEMINI"
rsync -a --delete "$SOURCE" "$GEMINI"
mkdir -p "$GEMINI_ARCHIFY"
rsync -a --delete "$ARCHIFY_SOURCE" "$GEMINI_ARCHIFY"
python3 "$ROOT/scripts/validate_repository.py"
echo "Build HTML Slides and bundled Archify distributions synchronized for Codex, Claude Code, and Gemini CLI."
